### PR TITLE
Added "Complete All" button for tasks

### PR DESCRIPTION
**Pull request by salocor**
Added "Complete All" button to complete all tasks. This was done by iterating through all tasks named "completed" and checking the boxes.

Also added padding after task list for better design with the new button.

### CODE REVIEW

**Comment by salocor** [comment]
This was just an idea I had for a feature. Not sure if it's too useful so don't feel bad denying it.

**Review by Dharmik48 — COMMENTED** [review]
LGTM🚀

**Comment by Dharmik48** [comment]
> This was just an idea I had for a feature. Not sure if it's too useful so don't feel bad denying it.

It indeed is a useful one! Thanks a lot for adding it😄

**Comment by Dharmik48** [comment]
This is good to merge now, thanks a lot for your valuable contribution 😄🚀

**Pull request merged**
