### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by neelakantan-ca**
Add description, installation guide, screenshots and contribution info

### CODE REVIEW

**Review by Dharmik48 — APPROVED** [review]
LGTM🚀

Thank you for contributing! Lets get this merged!

**Comment by neelakantan-ca** [comment]
Can #1 be closed then ?

**Comment by Dharmik48** [comment]
I think we can still add a `Thanks to all contributors` section like [this one](https://github.com/EddieHubCommunity/good-first-issue-finder#-thanks-to-all-contributors)

**Comment by neelakantan-ca** [comment]
Okay, will look into it and try to implement when I am free

**Comment by Dharmik48** [comment]
Alright! Whenever you get time.

**Pull request merged**
