### PR TITLE
hover for cancel colour - purple , and bg colour change for other btn.

### LINKED ISSUE #1: Improve the README
We need to add install steps, screenshots, etc., and properly organize the README

### PR DESCRIPTION
**Pull request by JayrajSingh65**
### Related Issue/Addition to code
- Hover for buttons 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Original | Updated
:----------------------:|:-----------:
** original screenshot  | ** updated screenshot **

https://user-images.githubusercontent.com/97652040/193402215-4dabe9f3-ef10-4127-8344-51ae008a8d71.mp4

### CODE REVIEW

**Comment by JayrajSingh65** [comment]
- some changes made to checked box also colour become green after task is competed.
- I hope you like these changes and this PR got merged very soon.

**Review by Dharmik48 — COMMENTED** [review]
It looks amazing! Awesome work @JayrajSingh65!

Thanks a lot for your contribution :)

**Comment by JayrajSingh65** [comment]
please add hacktober label so that it can be counted !

**Comment by JayrajSingh65** [comment]
- having any issue regarding this PR ?

**Comment by Dharmik48** [comment]
Thanks for the PR @JayrajSingh65! And sorry for the late review😅

Let's get it merged now!🚀

**Comment by JayrajSingh65** [comment]
> Thanks for the PR @JayrajSingh65! And sorry for the late review😅
> 
> Let's get it merged now!🚀

Finally 😅

**Pull request merged**
