### PR TITLE
Set new-task window height to a fixed amount and blurred the background on opening

### PR DESCRIPTION
**Pull request by salocor**
Turns out dynamically resizing an element based on text size is a chore so I settled on a fixed window with nice scrolling. I also added animations to blur the tasks for a cleaner look.

### CODE REVIEW

**Comment by salocor** [comment]
I also hosted this updated version at salocor.github.io/todo-list-app

**Review by Dharmik48 — CHANGES_REQUESTED** [review]
Hey @salocor, there is an issue where, if there are no tasks then the new task page is getting overflowed:
image

Can you fix that? And also there seems to be a merge conflict, so can you have a look at that?

**Comment by salocor** [comment]
Sure

**Comment by salocor** [comment]
Alright there we go I think I got it. Let me know if there's anything else you need me to do. 😄

**Review by salocor — COMMENTED** [review]
Got them all fixed.

Sorry I guess this just made a new comment. Still figuring out GitHub. 😁

**Review by Dharmik48 — APPROVED** [review]
LGTM🚀

**Comment by Dharmik48** [comment]
Great work @salocor! Thank you so much for contributing! 

Let's get it merged🚀

**Pull request merged**
